// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1:string,arg2:string):Promise<void>;

export function GetNotes(arg1:string):Promise<Array<string>>;

export function UpdateNote(arg1:string,arg2:string,arg3:number):Promise<void>;
